### ISSUE TITLE
Use logging module

### ISSUE THREAD

**Issue by jcsaaddupuy** [cam-stitt/arnold#9]
Currently, console output is done with a print statement.

It would be better if arnold would use the logging module and let the calling app decide what and how to log its output.

**Comment by jcsaaddupuy** [comment]
Also, using the 'print' argument raise an invalid syntax when used with arnold.main (python 2.7.8) :
```python
arnold.main(
    print=args.debug,
    database=db.get_database(),
    migration_module="project.migrations",
    directory='path/to/migrations'
)
```
This fail becauseof the name 'print' is a reserved python built-in name.
```
Traceback (most recent call last):
  File "/Users/jc/.virtualenvs/project-278/bin/project", line 9, in <module>
    load_entry_point('project==0.1', 'console_scripts', 'project')()
  File "/Users/jc/.virtualenvs/project-278/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jc/.virtualenvs/project-278/lib/python2.7/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/Users/jc/.virtualenvs/project-278/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/Users/jc/src/project-278/project/src/project/bin/cli.py", line 187
    print=args.debug,
        ^
SyntaxError: invalid syntax
```


For now, the only workaround seems to pass arguments as a dict :

```python
arnold_kwargs = {
    'print': args.debug,
    'database': db.get_database(),
    'migration_module': "project.migrations",
    'directory':'path/to/migrations'
       
}
arnold.main(
        **arnold_kwargs
)
```

Using the logging module also solve this issue.

**Comment by cam-stitt** [comment]
Thanks for this.
